// Comprehensive prescription templates for different medical specialties in Bangladesh

export interface TemplateField {
  label: string;
  value: string;
}

export interface TemplateSection {
  id: string;
  title: string;
  enabled: boolean;
  order: number;
  fields?: TemplateField[];
}

export interface PrescriptionTemplate {
  id: string;
  name: string;
  namebn: string;
  description: string;
  specialty: string;
  sections: TemplateSection[];
}

export const prescriptionTemplates: PrescriptionTemplate[] = [
  {
    id: "general_medicine",
    name: "General Medicine",
    namebn: "জেনারেল মেডিসিন",
    description: "For general physicians and internal medicine",
    specialty: "General Practice",
    sections: [
      { id: "cc", title: "Presenting Complains:", enabled: true, order: 1 },
      {
        id: "ph",
        title: "P/H:",
        enabled: true,
        order: 2,
        fields: [
          { label: "IHD", value: "" },
          { label: "HTN", value: "" },
          { label: "DM", value: "" },
          { label: "CKD", value: "" },
          { label: "CVD/PAD", value: "" },
          { label: "Thyroid", value: "" },
          { label: "BA/COPD", value: "" },
          { label: "Dyslipidaemia", value: "" },
        ],
      },
      { id: "oe", title: "On Examination:", enabled: true, order: 3 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 4 },
      { id: "adv", title: "Advice:", enabled: true, order: 5 },
      { id: "instructions", title: "Instructions:", enabled: true, order: 6 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 7 },
    ],
  },
  {
    id: "cardiology",
    name: "Cardiology",
    namebn: "কার্ডিওলজি",
    description: "For heart specialists",
    specialty: "Cardiology",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "ph",
        title: "Past History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "IHD/MI", value: "" },
          { label: "HTN", value: "" },
          { label: "DM", value: "" },
          { label: "Dyslipidaemia", value: "" },
          { label: "CHF", value: "" },
          { label: "Arrhythmia", value: "" },
          { label: "PCI/CABG", value: "" },
          { label: "Stroke", value: "" },
          { label: "Smoking", value: "" },
          { label: "Family Hx", value: "" },
        ],
      },
      {
        id: "cv_exam",
        title: "CVS Examination:",
        enabled: true,
        order: 3,
        fields: [
          { label: "BP", value: "" },
          { label: "Pulse", value: "" },
          { label: "JVP", value: "" },
          { label: "Heart Sound", value: "" },
          { label: "Murmur", value: "" },
          { label: "Peripheral Pulse", value: "" },
          { label: "Edema", value: "" },
        ],
      },
      { id: "inv", title: "Investigations:", enabled: true, order: 4 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 5 },
      { id: "adv", title: "Management:", enabled: true, order: 6 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 7 },
    ],
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    namebn: "চক্ষু বিশেষজ্ঞ",
    description: "For eye specialists",
    specialty: "Ophthalmology",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "ph",
        title: "Ocular History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "DM", value: "" },
          { label: "HTN", value: "" },
          { label: "Glaucoma", value: "" },
          { label: "Cataract", value: "" },
          { label: "Eye Surgery", value: "" },
          { label: "Glasses/Lens", value: "" },
        ],
      },
      {
        id: "vision",
        title: "Visual Acuity:",
        enabled: true,
        order: 3,
        fields: [
          { label: "RE (Distant)", value: "" },
          { label: "LE (Distant)", value: "" },
          { label: "RE (Near)", value: "" },
          { label: "LE (Near)", value: "" },
        ],
      },
      {
        id: "eye_exam",
        title: "Eye Examination:",
        enabled: true,
        order: 4,
        fields: [
          { label: "Lids/Lashes", value: "" },
          { label: "Conjunctiva", value: "" },
          { label: "Cornea", value: "" },
          { label: "AC", value: "" },
          { label: "Iris", value: "" },
          { label: "Pupil", value: "" },
          { label: "Lens", value: "" },
          { label: "IOP", value: "" },
          { label: "Fundus", value: "" },
        ],
      },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 5 },
      { id: "adv", title: "Advice:", enabled: true, order: 6 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 7 },
    ],
  },
  {
    id: "dentistry",
    name: "Dentistry",
    namebn: "দন্ত চিকিৎসা",
    description: "For dental practitioners",
    specialty: "Dentistry",
    sections: [
      { id: "cc", title: "Chief Complaint:", enabled: true, order: 1 },
      {
        id: "dental_hx",
        title: "Dental History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Previous Tx", value: "" },
          { label: "Extraction", value: "" },
          { label: "Filling", value: "" },
          { label: "Root Canal", value: "" },
          { label: "Denture", value: "" },
          { label: "Allergy", value: "" },
        ],
      },
      {
        id: "oral_exam",
        title: "Oral Examination:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Lips/Mucosa", value: "" },
          { label: "Gingiva", value: "" },
          { label: "Tongue", value: "" },
          { label: "Teeth", value: "" },
          { label: "Occlusion", value: "" },
          { label: "TMJ", value: "" },
        ],
      },
      { id: "tooth_chart", title: "Tooth Chart:", enabled: true, order: 4 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 5 },
      { id: "tx_plan", title: "Treatment Plan:", enabled: true, order: 6 },
      { id: "adv", title: "Advice:", enabled: true, order: 7 },
      { id: "followup", title: "Next Visit:", enabled: true, order: 8 },
    ],
  },
  {
    id: "pediatrics",
    name: "Pediatrics",
    namebn: "শিশু বিশেষজ্ঞ",
    description: "For child specialists",
    specialty: "Pediatrics",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "birth_hx",
        title: "Birth History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Term", value: "" },
          { label: "Mode", value: "" },
          { label: "Birth Wt", value: "" },
          { label: "Complications", value: "" },
        ],
      },
      {
        id: "dev_hx",
        title: "Developmental Hx:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Motor", value: "" },
          { label: "Social", value: "" },
          { label: "Language", value: "" },
        ],
      },
      {
        id: "immunization",
        title: "Immunization:",
        enabled: true,
        order: 4,
      },
      {
        id: "feeding",
        title: "Feeding History:",
        enabled: true,
        order: 5,
      },
      {
        id: "anthro",
        title: "Anthropometry:",
        enabled: true,
        order: 6,
        fields: [
          { label: "Weight", value: "" },
          { label: "Height", value: "" },
          { label: "HC", value: "" },
          { label: "MUAC", value: "" },
        ],
      },
      { id: "oe", title: "Examination:", enabled: true, order: 7 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 8 },
      { id: "adv", title: "Advice:", enabled: true, order: 9 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 10 },
    ],
  },
  {
    id: "dermatology",
    name: "Dermatology",
    namebn: "চর্মরোগ বিশেষজ্ঞ",
    description: "For skin specialists",
    specialty: "Dermatology",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "skin_hx",
        title: "Dermatological Hx:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Duration", value: "" },
          { label: "Site", value: "" },
          { label: "Progression", value: "" },
          { label: "Itching", value: "" },
          { label: "Pain", value: "" },
          { label: "Previous Rx", value: "" },
          { label: "Allergy", value: "" },
        ],
      },
      {
        id: "skin_exam",
        title: "Skin Examination:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Site", value: "" },
          { label: "Type", value: "" },
          { label: "Distribution", value: "" },
          { label: "Color", value: "" },
          { label: "Surface", value: "" },
          { label: "Border", value: "" },
        ],
      },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 4 },
      { id: "inv", title: "Investigations:", enabled: true, order: 5 },
      { id: "adv", title: "Treatment:", enabled: true, order: 6 },
      { id: "instructions", title: "Instructions:", enabled: true, order: 7 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 8 },
    ],
  },
  {
    id: "gynecology",
    name: "Gynecology & Obstetrics",
    namebn: "স্ত্রীরোগ ও প্রসূতি",
    description: "For gynecologists and obstetricians",
    specialty: "Gynecology",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "obs_hx",
        title: "Obstetric History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "G", value: "" },
          { label: "P", value: "" },
          { label: "A", value: "" },
          { label: "L", value: "" },
          { label: "LMP", value: "" },
          { label: "EDD", value: "" },
        ],
      },
      {
        id: "menstrual",
        title: "Menstrual History:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Menarche", value: "" },
          { label: "Cycle", value: "" },
          { label: "Duration", value: "" },
          { label: "Flow", value: "" },
          { label: "LMP", value: "" },
        ],
      },
      { id: "oe", title: "Examination:", enabled: true, order: 4 },
      { id: "pv", title: "P/V Examination:", enabled: true, order: 5 },
      { id: "inv", title: "Investigations:", enabled: true, order: 6 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 7 },
      { id: "adv", title: "Management:", enabled: true, order: 8 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 9 },
    ],
  },
  {
    id: "ent",
    name: "ENT (Otolaryngology)",
    namebn: "নাক, কান, গলা",
    description: "For ENT specialists",
    specialty: "ENT",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "ent_hx",
        title: "ENT History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Ear Discharge", value: "" },
          { label: "Hearing Loss", value: "" },
          { label: "Tinnitus", value: "" },
          { label: "Vertigo", value: "" },
          { label: "Nasal Block", value: "" },
          { label: "Throat Pain", value: "" },
          { label: "Voice Change", value: "" },
        ],
      },
      {
        id: "ear_exam",
        title: "Ear Examination:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Pinna", value: "" },
          { label: "EAC", value: "" },
          { label: "TM", value: "" },
          { label: "Hearing", value: "" },
        ],
      },
      {
        id: "nose_exam",
        title: "Nose Examination:",
        enabled: true,
        order: 4,
        fields: [
          { label: "External", value: "" },
          { label: "Septum", value: "" },
          { label: "Turbinates", value: "" },
          { label: "DNS", value: "" },
        ],
      },
      {
        id: "throat_exam",
        title: "Throat Examination:",
        enabled: true,
        order: 5,
        fields: [
          { label: "Tonsils", value: "" },
          { label: "Pharynx", value: "" },
          { label: "Larynx", value: "" },
        ],
      },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 6 },
      { id: "adv", title: "Treatment:", enabled: true, order: 7 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 8 },
    ],
  },
  {
    id: "orthopedics",
    name: "Orthopedics",
    namebn: "অর্থোপেডিক্স",
    description: "For bone and joint specialists",
    specialty: "Orthopedics",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "ortho_hx",
        title: "History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Trauma", value: "" },
          { label: "Pain", value: "" },
          { label: "Swelling", value: "" },
          { label: "Deformity", value: "" },
          { label: "Movement", value: "" },
          { label: "Previous Surgery", value: "" },
        ],
      },
      {
        id: "local_exam",
        title: "Local Examination:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Look", value: "" },
          { label: "Feel", value: "" },
          { label: "Move", value: "" },
          { label: "ROM", value: "" },
          { label: "Neurovascular", value: "" },
        ],
      },
      { id: "inv", title: "Investigations:", enabled: true, order: 4 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 5 },
      { id: "tx", title: "Treatment Plan:", enabled: true, order: 6 },
      { id: "adv", title: "Advice:", enabled: true, order: 7 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 8 },
    ],
  },
  {
    id: "psychiatry",
    name: "Psychiatry",
    namebn: "মনোরোগ বিশেষজ্ঞ",
    description: "For mental health specialists",
    specialty: "Psychiatry",
    sections: [
      { id: "cc", title: "Presenting Complaints:", enabled: true, order: 1 },
      {
        id: "psych_hx",
        title: "Psychiatric History:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Duration", value: "" },
          { label: "Onset", value: "" },
          { label: "Course", value: "" },
          { label: "Precipitants", value: "" },
          { label: "Previous Illness", value: "" },
          { label: "Treatment Hx", value: "" },
        ],
      },
      {
        id: "mse",
        title: "Mental State Exam:",
        enabled: true,
        order: 3,
        fields: [
          { label: "Appearance", value: "" },
          { label: "Behavior", value: "" },
          { label: "Speech", value: "" },
          { label: "Mood", value: "" },
          { label: "Affect", value: "" },
          { label: "Thought", value: "" },
          { label: "Perception", value: "" },
          { label: "Cognition", value: "" },
          { label: "Insight", value: "" },
        ],
      },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 4 },
      { id: "adv", title: "Management:", enabled: true, order: 5 },
      { id: "instructions", title: "Instructions:", enabled: true, order: 6 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 7 },
    ],
  },
  {
    id: "neurology",
    name: "Neurology",
    namebn: "স্নায়ুরোগ বিশেষজ্ঞ",
    description: "For neurologists",
    specialty: "Neurology",
    sections: [
      { id: "cc", title: "Chief Complaints:", enabled: true, order: 1 },
      {
        id: "neuro_hx",
        title: "Neurological Hx:",
        enabled: true,
        order: 2,
        fields: [
          { label: "Headache", value: "" },
          { label: "Seizure", value: "" },
          { label: "Weakness", value: "" },
          { label: "Numbness", value: "" },
          { label: "Vision", value: "" },
          { label: "Speech", value: "" },
          { label: "Memory", value: "" },
        ],
      },
      {
        id: "neuro_exam",
        title: "Neurological Exam:",
        enabled: true,
        order: 3,
        fields: [
          { label: "GCS", value: "" },
          { label: "Higher Function", value: "" },
          { label: "Cranial Nerves", value: "" },
          { label: "Motor System", value: "" },
          { label: "Sensory", value: "" },
          { label: "Reflexes", value: "" },
          { label: "Coordination", value: "" },
          { label: "Gait", value: "" },
        ],
      },
      { id: "inv", title: "Investigations:", enabled: true, order: 4 },
      { id: "dx", title: "Diagnosis:", enabled: true, order: 5 },
      { id: "adv", title: "Management:", enabled: true, order: 6 },
      { id: "followup", title: "Follow Up:", enabled: true, order: 7 },
    ],
  },
];

export const getTemplateById = (id: string): PrescriptionTemplate | undefined => {
  return prescriptionTemplates.find((template) => template.id === id);
};

export const getTemplatesBySpecialty = (specialty: string): PrescriptionTemplate[] => {
  return prescriptionTemplates.filter((template) => template.specialty === specialty);
};
